// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMuFnJvw6_guyy2ZRIoOzAYhwspdwL8Uc',
    appId: '1:387704115535:web:538ba38b02aa53c2a7753a',
    messagingSenderId: '387704115535',
    projectId: 'memory-notes-b55d7',
    authDomain: 'memory-notes-b55d7.firebaseapp.com',
    storageBucket: 'memory-notes-b55d7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC4R_Wjh1GmyNog1wepsdvFwGLHvS99IPY',
    appId: '1:387704115535:android:778bf1a8a96567c0a7753a',
    messagingSenderId: '387704115535',
    projectId: 'memory-notes-b55d7',
    storageBucket: 'memory-notes-b55d7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAb8gTP-1RrExSIX12D3vOdkhDaM9vm8jw',
    appId: '1:387704115535:ios:55f2e5b6fe6424a2a7753a',
    messagingSenderId: '387704115535',
    projectId: 'memory-notes-b55d7',
    storageBucket: 'memory-notes-b55d7.firebasestorage.app',
    iosBundleId: 'com.mastertechsoftware.memoryNotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAb8gTP-1RrExSIX12D3vOdkhDaM9vm8jw',
    appId: '1:387704115535:ios:55f2e5b6fe6424a2a7753a',
    messagingSenderId: '387704115535',
    projectId: 'memory-notes-b55d7',
    storageBucket: 'memory-notes-b55d7.firebasestorage.app',
    iosBundleId: 'com.mastertechsoftware.memoryNotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMuFnJvw6_guyy2ZRIoOzAYhwspdwL8Uc',
    appId: '1:387704115535:web:8fa2b2e7ea3c5596a7753a',
    messagingSenderId: '387704115535',
    projectId: 'memory-notes-b55d7',
    authDomain: 'memory-notes-b55d7.firebaseapp.com',
    storageBucket: 'memory-notes-b55d7.firebasestorage.app',
  );
}
